Homework7
AndersenSemenov/SPbU-hometask pull request #8
Opened 2020-12-06 09:09 UTC by AndersenSemenov

7 домашка

2020-12-07 09:15 UTC, gsvgit requested changes

2020-12-07 09:15 UTC, gsvgit commented on tests/hw7Tests/hw7Tests.fs
> +        testCase "test#1 concat method"  <| fun _ ->
Конкатинацию тоже можно потестировать через конкатинацию рандомных списков. Результат должен быть такой же как и при конкатенации обычных списков.

2020-12-07 09:15 UTC, gsvgit commented on tests/hw7Tests/hw7Tests.fs
> +            Expect.equal (concat lst1 lst2) res "Smth went wrong, expected another list"
Не вижу тестов на iter

2020-12-07 09:15 UTC, gsvgit commented on Homework7/MyList.fs
> +    | Head of 't
Head --- плохое название. Тут должно быть что-то от синглтона или чего-то похожего.

2020-12-07 09:15 UTC, gsvgit commented on Homework7/MyList.fs
> +let rec fold f acc lst =
Раз уж у Вас написан фолд, то длина через него замечательно выражается.

2020-12-07 09:15 UTC, gsvgit commented on Homework7/MyList.fs
> +            if opComp head1 head2 then Cons(head2, _go (Cons(head1, tail)))
ещё раз. Либо 
```
if ... then ... else
```
Либо уже
```
if
then
else
```

2020-12-07 09:15 UTC, gsvgit commented on Homework7/MyList.fs
> +let rec transform lst =
Посмотрите, как в стандартных модулях подобные функции называются и сделайте так же.

2020-12-07 09:15 UTC, gsvgit commented on Homework7/MyList.fs
> +let myListSort lst opComp =
Зачем вдруг этот странный префикс появился?

2020-12-07 09:15 UTC, gsvgit commented on Homework7/MyString.fs
> +let myStringConcat (str1: MyList<char>) (str2: MyList<char>) =
Я бы ожидал тут в каяестве типа MyString увидеть.

2020-12-07 09:15 UTC, gsvgit commented on Homework7/MyTree.fs
> +let getAverage tree =
Обе эти функции выражаются через некую универсальную функцию обхода. Придумайте и реализуйте её.

2020-12-07 09:15 UTC, gsvgit commented on tests/hw7Tests/hw7Tests.fs
> +                let a = List.fold (fun x y -> x+y) 0 lst
Гы-гы. Добавьте, пожалуйста, тест, который покажет, что направление свёртки правильное.

2020-12-07 09:15 UTC, gsvgit commented on tests/hw7Tests/hw7Tests.fs
> +                let a = List.map (fun x -> x+1) lst |> transform
Ну и пробелы у бинрных операций не надо забывать.

2020-12-07 09:15 UTC, gsvgit commented on Homework7/MyString.fs
> +let transformToMyString str =
И тут зачем-то префикс.

2020-12-08 05:45 UTC, gsvgit requested changes

2020-12-08 05:45 UTC, gsvgit commented on Homework7/MyTree.fs
> +    let s, q = _go (0, 0) (fun (sum, quantity) x -> (sum+x), (quantity+1)) tree
Пробелы вокруг бинарных операций.

2020-12-08 05:45 UTC, gsvgit commented on Homework7/MyTree.fs
> +let rec _go acc func (tree: MyTree<int>) =
А нельзя ли ей какое-то вменяемое имя дать?

2020-12-08 05:45 UTC, gsvgit commented on tests/hw7Tests/hw7Tests.fs
> +                let h = [lst1; lst2] |> Seq.ofList
Что-то сложно. конкатенация двух списков --- это просто ```@```

2020-12-08 05:45 UTC, gsvgit commented on tests/hw7Tests/hw7Tests.fs
> +                let a = List.fold (fun x y -> x - y) 1 lst
А что, на делении не работает?

2020-12-08 05:45 UTC, gsvgit commented on tests/hw7Tests/hw7Tests.fs
> +                let a = List.map (fun x -> x + 1) lst |> toMyList
Думается, лучше функции, которые Вы применяете в мапе, итере и прочих фолдах вынести и назвать, чтобы менять в одном месте, а не в двух.

2020-12-08 05:53 UTC, AndersenSemenov commented on tests/hw7Tests/hw7Tests.fs
> +                let a = List.fold (fun x y -> x - y) 1 lst
Вы имеете в виду ещё один тест на деление добавить? Я просто изначально не добавил потому что y может быть 0, при делении может exception вылетать, нужно ещё один if писать, с '-' попроще.

2020-12-08 06:26 UTC, gsvgit commented
Вычитание ничего не говорить про ассоциативность. Если сложно с делением,
то можете другую операцию придумать, И почему if, когда можно просто фильтр
прикрутить?
Regards,
Semyon Grigorev.


вт, 8 дек. 2020 г. в 08:53, AndersenSemenov <notifications@github.com>:

> *@AndersenSemenov* commented on this pull request.
> ------------------------------
>
> In tests/hw7Tests/hw7Tests.fs
> <https://github.com/AndersenSemenov/SPbU-hometask/pull/8#discussion_r538054844>
> :
>
> > +            then
>
> +                Expect.equal (List.length lst) (lst |> toMyList |> getLength) "My Length method has to work as system"
>
> +        testProperty "Comparing results of Sorts" <| fun (lst:list<int>) ->
>
> +            if List.length lst <> 0
>
> +            then
>
> +                Expect.equal (List.sort lst|> toMyList) (sort (lst |> toMyList) (fun x y -> x > y)) "My Sort has to work as system"
>
> +        testProperty "Comparing results of Map method" <| fun (lst:list<int>) ->
>
> +            if List.length lst <> 0
>
> +            then
>
> +                let a = List.map (fun x -> x + 1) lst |> toMyList
>
> +                let b = lst |> toMyList |> map (fun x -> x + 1)
>
> +                Expect.equal a b "My Map has to work as system"
>
> +        testProperty "Comparing results of Fold method" <| fun (lst:list<int>) ->
>
> +            if List.length lst <> 0
>
> +            then
>
> +                let a = List.fold (fun x y -> x - y) 1 lst
>
>
> Вы имеете в виду ещё один тест на деление добавить? Я просто изначально не
> добавил потому что y может быть 0, при делении может exception вылетать,
> нужно ещё один if писать, с '-' попроще.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/AndersenSemenov/SPbU-hometask/pull/8#discussion_r538054844>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAA2CQHWYPZSCKYBFO7IGGTSTW5PLANCNFSM4UPFUESA>
> .
>

2020-12-12 10:48 UTC, gsvgit approved these changes

2020-12-12 10:48 UTC, gsvgit commented on Homework7/MyTree.fs
> +open MyList
Интереса ради сравните с самой первой версией. Кода меньше и он аккуратнее. Всегда бы так и, желательно, с первого раза .... Но это я размечтался, конечно.

2020-12-14 07:09 UTC, merged